version: '3'
services:
  backend:
    image: cabreraevil/psintegra-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    container_name: psintegra-backend
    command: npm start
