const disorders = [
    'abuso de drogas',
    'abuso de sustancias',
    'codependencia',
    'depresión',
    'desorden alimenticio',
    'desorden emocional',
    'duelo',
    'inestabilidad emocional',
    'insomnio',
    'irritabilidad',
    'maltrato emocional',
    'miedo',
    'psiquiatría',
    'psitacosis',
    'trastorno alimentario',
    'ansiedad',
    'estrés postraumático',
    'trastorno de personalidad',
    'trastorno emocional',
    'obsesivo compulsivo',
    'psicológico',
    'psiquiátrico',
    'estado de ánimo',
    'sueño',
    'adicción',
    'agorafobia',
    'esquizofrenia',
    'fobia social',
    'hipocondría',
    'trastorno de pánico',
    'trastorno dismórfico corporal',
    'trastorno límite de la personalidad',
    'trastorno obsesivo-compulsivo de la personalidad',
    'trastorno por déficit de atención e hiperactividad',
    'trastorno por estrés postraumático complejo',
    'trastorno por uso de alcohol',
    'trastorno por uso de sustancias',
    'trastorno reactivo del apego',
    'tricotilomanía',
    'tristeza',
    'violencia doméstica',
    'alcoholismo',
    'autismo',
    'depresión mayor',
    'distorsión de la realidad',
    'epilepsia',
    'fobia',
    'trastorno del sueño',
    'trastorno depresivo mayor',
    'trastorno esquizoafectivo',
    'trastorno límite de la personalidad',
    'trastorno por uso de sustancias opiáceas',
    'trastorno por uso de alucinógenos',
    'trastorno por uso de tabaco'
];

module.exports = disorders;