const gratitude = [
    'gracias',
    'muchas gracias',
    'te agradezco',
    'agradecido/a',
    'aprecio',
    'reconocimiento',
    'gratitud',
    'mil gracias',
    'te estoy muy agradecido/a',
    'te doy las gracias',
    'un sincero agradecimiento',
    'estoy enormemente agradecido/a',
    'te lo agradezco de corazón',
    'no tengo palabras para agradecerte',
    'infinitas gracias',
    'eres muy amable',
    'te estoy eternamente agradecido/a',
    'no sé cómo agradecerte lo suficiente',
    'valoro mucho tu ayuda',
    'me has hecho un gran favor',
    'estoy muy agradecido/a por tu generosidad',
    'no puedo expresar lo agradecido/a que estoy',
    'eres una persona maravillosa',
    'te agradezco de todo corazón',
    'tu apoyo significa mucho para mí',
    'eres increíble',
    'te estoy inmensamente agradecido/a',
    'eres un ángel',
    'eres un/una salvador/a',
    'qué haría sin ti',
    'tus acciones hablan más que mil palabras',
    'no sé qué habría hecho sin ti',
    'eres una bendición',
    'te estoy profundamente agradecido/a',
    'te debo mucho',
    'gracias por ser tan amable',
    'no puedo agradecerte lo suficiente',
    'tus palabras significan mucho para mí',
    'eres un verdadero amigo/a',
    'me has dado tanto',
    'tu ayuda ha sido invaluable',
    'estoy agradecido/a por tu amabilidad',
    'eres una persona especial',
    'eres una inspiración para mí',
    'eres un modelo a seguir',
    'eres alguien a quien admiro',
    'te agradezco de todo el corazón'
];

module.exports = gratitude;