const greetings = [
    'hola',
    'buenos días',
    'buenas tardes',
    'buenas noches',
    'estás',
    'qué',
    'tal',
    'va',
    'saludos',
    'ayudarte',
    'bienvenido',
    'sesión',
    'sientes',
    'cómo estás',
    'qué tal todo',
    'cómo te va',
    'qué hay de nuevo',
    'qué pasa',
    'cómo te encuentras',
    'espero que estés bien',
    'qué tal ha sido tu día',
    'cómo te sientes hoy',
    'qué novedades tienes',
    'qué te trae por aquí',
    'espero que tengas un buen día',
    'qué te trae buenos deseos',
    'qué te anima hoy',
    'cómo va todo',
    'qué tal te trata la vida',
    'qué te pone de buen humor',
    'cómo ha sido tu semana',
    'qué te emociona',
    'qué tal te ha ido',
    'qué alegrías tienes',
    'cómo va tu mundo',
    'qué te hace sonreír',
    'cómo te has sentido últimamente',
    'qué te inspira',
    'qué novedades tienes para contar',
    'cómo te has estado llevando',
    'qué te entusiasma',
    'qué te anima a seguir adelante',
    'cómo va tu día hasta ahora',
    'qué te hace feliz',
    'cómo estuvo tu fin de semana',
    'qué te trae buenas energías',
    'qué tal ha sido tu mes',
    'cómo te trata la vida',
    'qué te pone de buen ánimo',
    'qué te motiva',
    'cómo te ha ido últimamente'
];

module.exports = greetings;