const hobbies = [
    'arte',
    'música',
    'deporte',
    'lectura',
    'viajes',
    'cocina',
    'juegos',
    'naturaleza',
    'tecnología',
    'baile',
    'senderismo',
    'fotografía',
    'pintura',
    'escritura',
    'ciclismo',
    'yoga',
    'jardinería',
    'pesca',
    'acampar',
    'patinaje',
    'natación',
    'ajedrez',
    'bricolaje',
    'birdwatching',
    'esquí',
    'gimnasia',
    'malabarismo',
    'meditación',
    'canto',
    'buceo',
    'kayak',
    'voluntariado',
    'cocina étnica',
    'puzzles',
    'teatro',
    'modelado de arcilla',
    'escalada',
    'paddleboarding',
    'esgrima',
    'parkour',
    'espeleología',
    'esquí acuático',
    'equitación',
    'surf',
    'dibujo',
    'cine',
    'bordado',
    'globoflexia',
    'dardos',
    'magia'
];

module.exports = hobbies;