const otherTopics = [
    'creatividad',
    'meditación',
    'mindfulness',
    'espiritualidad',
    'autoexpresión',
    'cambio personal',
    'superación',
    'motivación',
    'resiliencia',
    'autocuidado',
    'bienestar emocional',
    'hábitos saludables',
    'relajación',
    'equilibrio interior',
    'autenticidad',
    'paz interior',
    'gratitud',
    'visualización creativa',
    'empoderamiento personal',
    'transformación interna',
    'propósito de vida',
    'empatía',
    'aceptación personal',
    'crecimiento espiritual',
    'consciencia plena',
    'equilibrio emocional',
    'compasión',
    'autodesarrollo',
    'autenticidad',
    'energía positiva',
    'inteligencia emocional',
    'autotrascendencia',
    'apreciación de la belleza',
    'intuición',
    'autocontrol',
    'autoconciencia',
    'autolibertad',
    'creación de hábitos positivos',
    'autodisciplina',
    'autocompasión',
    'gratitud',
    'desapego',
    'aceptación del cambio',
    'autoaceptación',
    'crecimiento personal',
    'conexión interna',
    'búsqueda de significado',
    'equilibrio mente-cuerpo',
    'conexión con la naturaleza',
    'despertar espiritual'
];

module.exports = otherTopics;