const personalDevelopment = [
    'crecimiento personal',
    'motivación',
    'metas',
    'tomar decisiones',
    'autodescubrimiento',
    'procrastinación',
    'resolución de problemas',
    'gestión del tiempo',
    'autoconfianza',
    'autoestima',
    'autoconocimiento',
    'autoaceptación',
    'desarrollo de habilidades',
    'superación personal',
    'aprendizaje continuo',
    'desarrollo profesional',
    'creatividad',
    'liderazgo',
    'empoderamiento',
    'resiliencia',
    'adaptabilidad',
    'gestión del cambio',
    'enfoque positivo',
    'tolerancia a la frustración',
    'gestión emocional',
    'equilibrio vida-trabajo',
    'autoevaluación',
    'planificación',
    'autodisciplina',
    'pensamiento crítico',
    'comunicación efectiva',
    'aprendizaje autodirigido',
    'gestión de proyectos',
    'gestión del estrés',
    'creación de hábitos saludables',
    'autonomía',
    'empatía',
    'creación de redes de apoyo',
    'inteligencia emocional',
    'aprendizaje de idiomas',
    'optimización del rendimiento',
    'concentración',
    'perseverancia',
    'auto-motivación',
    'resolución de conflictos',
    'crecimiento espiritual',
    'transformación personal',
    'equilibrio personal',
    'autenticidad'
];

module.exports = personalDevelopment;