const problems = [
    'problemas',
    'aflicción',
    'ansia',
    'ansiedad',
    'cansancio',
    'desánimo',
    'desasosiego',
    'desesperación',
    'desgaste emocional',
    'desmotivación',
    'emociones negativas',
    'frustración',
    'herida emocional',
    'heridas del alma',
    'lucha emocional',
    'preocupación',
    'emocionales',
    'familiares',
    'laborales',
    'trauma',
    'tristeza',
    'vulnerabilidad emocional',
    'inseguridad',
    'soledad',
    'confusión',
    'estrés',
    'ira',
    'culpa',
    'inquietud',
    'miedo',
    'angustia',
    'depresión',
    'agotamiento',
    'desesperanza',
    'desilusión',
    'resentimiento',
    'desconexión emocional',
    'pérdida',
    'desorden mental',
    'desequilibrio emocional',
    'insatisfacción',
    'tensión',
    'incertidumbre',
    'insomnio',
    'pesimismo',
    'incomprensión',
    'enfado',
    'desgaste personal',
    'adversidad',
    'inestabilidad emocional'
];

module.exports = problems;