const psychologistTopics = [
    'psicología',
    'estrés',
    'autoestima',
    'duelo',
    'ansiedad',
    'terapia',
    'cognitivo',
    'conductual',
    'habilidades',
    'sociales',
    'insomnio',
    'depresión',
    'límites',
    'emociones',
    'trauma',
    'pareja',
    'salud',
    'bienestar',
    'laboral',
    'familiar',
    'autoconocimiento',
    'resiliencia',
    'paz',
    'autocontrol',
    'adicciones',
    'problemas emocionales',
    'trastornos de la alimentación',
    'adicción al trabajo',
    'autoaceptación',
    'confianza',
    'miedos',
    'manejo del estrés',
    'mejora personal',
    'relaciones interpersonales',
    'comunicación efectiva',
    'control de la ira',
    'crecimiento emocional',
    'desarrollo personal',
    'establecimiento de metas',
    'gestión emocional',
    'motivación',
    'optimismo',
    'superación personal',
    'aprendizaje emocional',
    'cambio de hábitos',
    'gestión del tiempo',
    'relaciones familiares',
    'resolución de conflictos'
];

module.exports = psychologistTopics;