const relationships = [
    'amor',
    'amistad',
    'relaciones de pareja',
    'relaciones familiares',
    'familia',
    'amigo',
    'amiga',
    'novio',
    'novia',
    'matrimonio',
    'divorcio',
    'separación',
    'infidelidad',
    'celos',
    'hermano',
    'hermana',
    'padre',
    'madre',
    'hijo',
    'hija',
    'hijos',
    'hijas',
    'tio',
    'tía',
    'abuelo',
    'abuela',
    'sobrino',
    'sobrina',
    'primo',
    'prima',
    'cuñado',
    'cuñada',
    'suegro',
    'suegra',
    'yerno',
    'nuera',
    'suegros',
    'suegras',
    'papá',
    'mamá',
    'papás',
    'mamás',
    'hijastro',
    'hijastra',
    'conflictos',
    'comunicación',
    'intimidad',
    'rupturas',
    'matrimonio'
];

module.exports = relationships;