const selfHelp = [
    'acompañamiento',
    'amor propio',
    'autoayuda',
    'autoconocimiento',
    'autocuidado',
    'autoestima',
    'autoexigencia',
    'bienestar',
    'capacidad de adaptación',
    'comunicación efectiva',
    'confianza en uno mismo',
    'consuelo',
    'cuidado personal',
    'desarrollo personal',
    'empatía',
    'energía emocional',
    'entendimiento interpersonal',
    'entrenamiento emocional',
    'equilibrio emocional',
    'esfuerzo personal',
    'fatiga',
    'felicidad',
    'fortalecimiento emocional',
    'habilidades sociales',
    'meditación',
    'optimismo',
    'orientación psicológica',
    'paciencia',
    'pareja',
    'paz mental',
    'perspectiva emocional',
    'problemas cotidianos',
    'recuperación emocional',
    'reducción del estrés',
    'rehabilitación emocional',
    'relajación',
    'resiliencia',
    'salud emocional',
    'salud mental',
    'sanación emocional',
    'satisfacción personal',
    'sexualidad',
    'aceptación',
    'autonomía',
    'autocontrol',
    'compasión',
    'crecimiento personal',
    'desarrollo espiritual',
    'equilibrio interior',
    'esperanza'
];

module.exports = selfHelp;