const therapy = [
    'cognitivo conductual',
    'consejería',
    'psicológica',
    'terapia de pareja',
    'terapia familiar',
    'terapia de grupo',
    'terapia de aceptación y compromiso',
    'terapia gestalt',
    'terapia humanista',
    'terapia breve',
    'terapia de juego',
    'terapia narrativa',
    'terapia de arte',
    'terapia de movimiento',
    'terapia psicodinámica',
    'terapia cognitiva',
    'terapia conductual',
    'terapia centrada en el cliente',
    'terapia sistémica',
    'terapia de apoyo',
    'terapia de modificación de conducta',
    'terapia de exposición',
    'terapia de relajación',
    'terapia de manejo del estrés',
    'terapia de resolución de problemas',
    'terapia de atención plena',
    'terapia de imagen guiada',
    'terapia de reestructuración cognitiva',
    'terapia de desensibilización y reprocesamiento por movimientos oculares',
    'terapia dialectical behavior',
    'terapia de esquemas',
    'terapia de conducta dialéctica',
    'terapia breve estratégica',
    'terapia basada en soluciones',
    'terapia racional emotiva',
    'terapia de psicodrama',
    'terapia multimodal',
    'terapia existencial',
    'terapia narrativa',
    'terapia integrativa',
    'terapia de pareja emocionalmente enfocada',
    'terapia cognitiva basada en la compasión',
    'terapia de arte gestáltica',
    'terapia basada en la aceptación y compromiso',
    'terapia de enfoque somático',
    'terapia de enfoque centrada en el trauma',
    'terapia de juego centrada en el cliente',
    'terapia centrada en soluciones',
    'terapia familiar sistémica',
    'terapia de grupo centrada en soluciones',
    'terapia de exposición y prevención de respuesta'
];

module.exports = therapy;