const workLife = [
'carrera profesional',
'equilibrio trabajo-vida',
'estrés laboral',
'relaciones laborales',
'desarrollo de habilidades',
'productividad',
'cambio de trabajo',
'reorientación profesional',
'liderazgo',
'gestión del tiempo',
'comunicación en el trabajo',
'motivación laboral',
'trabajo en equipo',
'resolución de conflictos laborales',
'crecimiento profesional',
'capacitación laboral',
'gestión del estrés en el trabajo',
'empoderamiento laboral',
'negociación salarial',
'gestión del cambio laboral',
'desarrollo de competencias laborales',
'administración del tiempo',
'establecimiento de metas laborales',
'networking',
'gestión del rendimiento',
'gestión de proyectos',
'mejora continua',
'creación de redes profesionales',
'toma de decisiones en el trabajo',
'desarrollo de liderazgo',
'manejo de conflictos laborales',
'planificación de la carrera profesional',
'autoevaluación laboral',
'adaptabilidad laboral',
'aprendizaje en el trabajo',
'gestión de equipos',
'creatividad en el trabajo',
'trabajo remoto',
'balance trabajo-familia',
'motivación en el trabajo',
'mentoring',
'aprendizaje continuo en el trabajo',
'desarrollo de talento',
'gestión de la diversidad en el trabajo',
'resiliencia en el trabajo',
'estrategias de trabajo eficientes',
'gestión de la carga laboral',
'planificación de proyectos',
'desarrollo de carrera en la empresa'
];

module.exports = workLife;